version: "3.9"
   
services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=mydatabase
      - POSTGRES_USER=mydatabaseuser
      - POSTGRES_PASSWORD=sosecure
  web:
    build: .
    entrypoint: ./docker-entrypoint.sh
    volumes:
      - ./resume_scanner:/usr/src/app/resume_scanner
      - ./resumes:/usr/src/app/resumes
      - ./nltk_data:/usr/local/nltk_data
      - ./docker-entrypoint.sh:/usr/src/app/docker-entrypoint.sh
    ports:
      - "8000:8000"
    depends_on:
      - db
    working_dir: /usr/src/app
